### ISSUE TITLE
UI/Interaction out of alignment

### ISSUE THREAD

**Issue by clipk0** [ThatRozebudDude/LethalCompany-FovAdjust#1]
When altering the FOV it changes the center of the screen and the UI and interact fields do not align properly. The higher the FOV the more the issue becomes apparent. 

For example: If I am looking at the ship open/close buttons, I would put the button I want to interact with in the center of my screen, the interact UI would populate, then you execute the interact button. When altering the FOV it no longer is in the center of the screen to interact. The UI of the finger to push the button is also off making it really hard to actually click the buttons you are trying to click.

**Comment by ThatRozebudDude** [comment]
Are you able to post a video of this happening to you? I tried testing this in-game and everything seems to be working fine and changing the FOV didn't seem to change anything about the area that you could interact with stuff.
