### ISSUE TITLE
FOV not changing

### ISSUE THREAD

**Issue by Theesl123** [ThatRozebudDude/LethalCompany-FovAdjust#4]
fov has reverted to normal, was working before...
![image_2023-12-13_210323196](https://github.com/ThatRozebudDude/LethalCompany-FovAdjust/assets/105258749/8d9b9c3e-c081-4bf7-9615-33602043d83e)
![image_2023-12-13_210348198](https://github.com/ThatRozebudDude/LethalCompany-FovAdjust/assets/105258749/7e421106-013d-402f-b21f-4de163fd342b)

**Comment by Theesl123** [comment]
nvm, found out it was being conflicted by other mods

**Comment by ThatRozebudDude** [comment]
What mod was conflicting with it? I'm looking into making sure this mod works with as many mods as possible so it would be nice to have a mod that I could test that I know conflicts with it,

**Comment by NeuTraLZero** [comment]
I found that my FOV is not changing with the Noise Suppression mod, for whatever reason

**Comment by Theesl123** [comment]
> What mod was conflicting with it? I'm looking into making sure this mod works with as many mods as possible so it would be nice to have a mod that I could test that I know conflicts with it,

sorry that im so late to respond to this
the main mod that was conflicting was more emotes by sligili https://thunderstore.io/c/lethal-company/p/Sligili/More_Emotes/
